web/router.ex
defmodule Autobeep.Router do
  use Autobeep.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Autobeep.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Autobeep do
    pipe_through :browser # Use the default browser stack
    get "/", PageController, :index
    resources "/vehicle", VehicleController
  end
  
  scope "/auth", Autobeep do
    pipe_through :browser

    get "/signout", AuthController, :signout

    # Request phase paths
    get "/:provider", AuthController, :request
    # Callback phase paths
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Autobeep do
  #   pipe_through :api
  # end
end

lib/autobeep/endpoint.ex
defmodule Autobeep.Endpoint do
  use Phoenix.Endpoint, otp_app: :autobeep

  socket "/socket", Autobeep.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :autobeep, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_autobeep_key",
    signing_salt: "pWuwOHgo"

  plug Autobeep.Router
end

lib/autobeep/repo.ex
defmodule Autobeep.Repo do
  use Ecto.Repo, otp_app: :autobeep
end

web/models/user.ex
defmodule Autobeep.User do
  use Autobeep.Web, :model

  schema "users" do
    field :email, :string
    field :provider, :string
    field :token, :string
    field :avatar_url, :string
    field :uuid_token, :string
    field :first_name, :string
    field :last_name, :string
    field :birth_date, :date
    field :phonenumber, :string
    has_many :vehicles, Autobeep.Vehicle

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:email, :provider, :token, :uuid_token, :avatar_url, :first_name, :last_name, :birth_date, :phonenumber])
    |> validate_required([:email, :provider, :token])
  end
end

web/models/vehicle.ex
defmodule Autobeep.Vehicle do
  use Autobeep.Web, :model

  schema "vehicles" do
    field :brand, :string
    field :reference, :string
    field :model, :string
    field :plate, :string
    field :mileage, :string
    field :type, :string
    belongs_to :user, Autobeep.User

    timestamps()
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:brand, :reference, :model, :plate, :mileage, :type])
    |> validate_required([:brand, :plate])
  end
end

web/controllers/auth_controller.ex
defmodule Autobeep.AuthController do
    use Autobeep.Web, :controller
    plug Ueberauth

    alias Autobeep.User

    def callback(conn, params) do
      %{ assigns: %{ ueberauth_auth: auth }} = conn
      %{"provider" => provider} = params
      user_params = %{
        token: auth.credentials.token,
        email: auth.info.email,
        provider: provider,
        avatar_url: auth.info.image,
        first_name: auth.info.first_name || auth.info.name,
        last_name: auth.info.last_name,
        phonenumber: auth.info.phone
      }
      changeset = User.changeset(%User{}, user_params)
      signin(conn, changeset)
    end

    defp signin(conn, changeset) do
      case insert_or_update_user(changeset) do
        {:ok, user} ->
          conn
          |> put_flash(:info, "Bienvenido #{user.first_name} #{user.last_name}!")
          |> put_session(:user_id, user.id)
          |> redirect(to: page_path(conn, :index))
        {:error, reason} ->
          IO.inspect(reason)
          conn
          |> put_flash(:error, "Error iniciando sesión.")
          |> redirect(to: page_path(conn, :index))
      end
    end

    def signout(conn, _params) do
      conn
      |> configure_session(drop: true)
      |> redirect(to: page_path(conn, :index))
    end

    defp insert_or_update_user(changeset) do
      case Repo.get_by(User, email: changeset.changes.email) do
        nil ->
          Repo.insert(changeset)
        user ->
          {:ok, user}
      end

    end
  end

web/controllers/page_controller.ex
defmodule Autobeep.PageController do
  use Autobeep.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/vehicle_controller.ex
defmodule Autobeep.VehicleController do
  use Autobeep.Web, :controller

  alias Autobeep.Vehicle
  
  plug Autobeep.Plugs.RequireAuth when action in [:index, :new, :create, :show, :edit, :update, :delete]
  plug :check_vehicle_owner when action in [:edit, :update, :delete]

  def index(conn, _params) do
    vehicles = Repo.all(Vehicle)
    render(conn, "index.html", vehicles: vehicles)
  end

  def new(conn, _params) do
    changeset = Vehicle.changeset(%Vehicle{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"vehicle" => vehicle_params}) do
    # This is the way to make an association
    IO.inspect conn.assigns.user
    changeset = conn.assigns.user
    |> build_assoc(:vehicles)
    |> Vehicle.changeset(vehicle_params)

    case Repo.insert(changeset) do
      {:ok, _vehicle} ->
        conn
        |> put_flash(:info, "Se creó correctamente el vehículo.")
        |> redirect(to: vehicle_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    vehicle = Repo.get!(Vehicle, id)
    render(conn, "show.html", vehicle: vehicle)
  end

  def edit(conn, %{"id" => id}) do
    vehicle = Repo.get!(Vehicle, id)
    changeset = Vehicle.changeset(vehicle)
    render(conn, "edit.html", vehicle: vehicle, changeset: changeset)
  end

  def update(conn, %{"id" => id, "vehicle" => vehicle_params}) do
    vehicle = Repo.get!(Vehicle, id)
    changeset = Vehicle.changeset(vehicle, vehicle_params)

    case Repo.update(changeset) do
      {:ok, vehicle} ->
        conn
        |> put_flash(:info, "Se actualizó correctamente el vehículo.")
        |> redirect(to: vehicle_path(conn, :show, vehicle))
      {:error, changeset} ->
        render(conn, "edit.html", vehicle: vehicle, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    vehicle = Repo.get!(Vehicle, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(vehicle)

    conn
    |> put_flash(:info, "Se eliminó correctamente el vehículo.")
    |> redirect(to: vehicle_path(conn, :index))
  end
  
  def check_vehicle_owner(conn, _params) do
    %{params: %{"id" => vehicle_id}} = conn
    if Repo.get(Vehicle, vehicle_id).user_id == conn.assigns.user.id do
      conn
    else
      conn
      |> put_flash(:error, "No eres el propietario del vehículo.")
      |> redirect(to: vehicle_path(conn, :index))
      |> halt()
    end
  end
end

web/views/error_view.ex
defmodule Autobeep.ErrorView do
  use Autobeep.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Autobeep.LayoutView do
  use Autobeep.Web, :view
end

web/views/page_view.ex
defmodule Autobeep.PageView do
  use Autobeep.Web, :view
end

web/views/vehicle_view.ex
defmodule Autobeep.VehicleView do
  use Autobeep.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Autobeep!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
            
  </head>

  <body>
    <nav class="light-blue">
      <div class="nav-wrapper container">
        <a href="/" class="brand-logo">
          Autobeep
        </a>
        <ul class="right">
          <%= if @conn.assigns[:user] do %>
            <li>
              <%= link "Cerrar sesión", to: auth_path(@conn, :signout) %>
            </li>
          <% else %>
            <li>
              <p>Inicia sesión con: </p>
            </li>
            <li>
              <%= link "FB", to: auth_path(@conn, :request, "facebook") %>
            </li>
            <li>
              <%= link "Google", to: auth_path(@conn, :request, "google") %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<%= if @conn.assigns[:user] do %>
<% else %>
  <div class="jumbotron">
    <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  </div>
<% end %>

web/templates/vehicle/edit.html.eex
<h2>Edit vehicle</h2>

<%= render "form.html", changeset: @changeset,
                        action: vehicle_path(@conn, :update, @vehicle) %>

<%= link "Back", to: vehicle_path(@conn, :index) %>

web/templates/vehicle/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :brand, class: "control-label" %>
    <%= text_input f, :brand, class: "form-control" %>
    <%= error_tag f, :brand %>
  </div>

  <div class="form-group">
    <%= label f, :reference, class: "control-label" %>
    <%= text_input f, :reference, class: "form-control" %>
    <%= error_tag f, :reference %>
  </div>

  <div class="form-group">
    <%= label f, :model, class: "control-label" %>
    <%= text_input f, :model, class: "form-control" %>
    <%= error_tag f, :model %>
  </div>

  <div class="form-group">
    <%= label f, :plate, class: "control-label" %>
    <%= text_input f, :plate, class: "form-control" %>
    <%= error_tag f, :plate %>
  </div>

  <div class="form-group">
    <%= label f, :mileage, class: "control-label" %>
    <%= text_input f, :mileage, class: "form-control" %>
    <%= error_tag f, :mileage %>
  </div>

  <div class="form-group">
    <%= label f, :type, class: "control-label" %>
    <%= text_input f, :type, class: "form-control" %>
    <%= error_tag f, :type %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/vehicle/index.html.eex
<h2>Listing vehicles</h2>

<table class="table">
  <thead>
    <tr>
      <th>Brand</th>
      <th>Reference</th>
      <th>Model</th>
      <th>Plate</th>
      <th>Mileage</th>
      <th>Type</th>
      <th>User</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for vehicle <- @vehicles do %>
    <tr>
      <td><%= vehicle.brand %></td>
      <td><%= vehicle.reference %></td>
      <td><%= vehicle.model %></td>
      <td><%= vehicle.plate %></td>
      <td><%= vehicle.mileage %></td>
      <td><%= vehicle.type %></td>
      <td><%= vehicle.user_id %></td>

      <td class="text-right">
        <%= link "Show", to: vehicle_path(@conn, :show, vehicle), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: vehicle_path(@conn, :edit, vehicle), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: vehicle_path(@conn, :delete, vehicle), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New vehicle", to: vehicle_path(@conn, :new) %>

web/templates/vehicle/new.html.eex
<h2>New vehicle</h2>

<%= render "form.html", changeset: @changeset,
                        action: vehicle_path(@conn, :create) %>

<%= link "Back", to: vehicle_path(@conn, :index) %>

web/templates/vehicle/show.html.eex
<h2>Show vehicle</h2>

<ul>

  <li>
    <strong>Brand:</strong>
    <%= @vehicle.brand %>
  </li>

  <li>
    <strong>Reference:</strong>
    <%= @vehicle.reference %>
  </li>

  <li>
    <strong>Model:</strong>
    <%= @vehicle.model %>
  </li>

  <li>
    <strong>Plate:</strong>
    <%= @vehicle.plate %>
  </li>

  <li>
    <strong>Mileage:</strong>
    <%= @vehicle.mileage %>
  </li>

  <li>
    <strong>Type:</strong>
    <%= @vehicle.type %>
  </li>

  <li>
    <strong>User:</strong>
    <%= @vehicle.user_id %>
  </li>

</ul>

<%= link "Edit", to: vehicle_path(@conn, :edit, @vehicle) %>
<%= link "Back", to: vehicle_path(@conn, :index) %>